/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Camera: typeof import('./components/mainMid/camera.vue')['default']
    Cesium: typeof import('./components/mainMid/cesium.vue')['default']
    EchartMap: typeof import('./components/mainMid/echartMap.vue')['default']
    EchartTl: typeof import('./components/mainRight/echartsR1/echartTl.vue')['default']
    EchartTx: typeof import('./components/mainRight/echartsR1/echartTx.vue')['default']
    EhartCc: typeof import('./components/mainRight/echartsR1/ehartCc.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Left1: typeof import('./components/mainLeft/left1.vue')['default']
    Left2: typeof import('./components/mainLeft/left2.vue')['default']
    Left3: typeof import('./components/mainLeft/left3.vue')['default']
    Left4: typeof import('./components/mainLeft/left4.vue')['default']
    MapCopy: typeof import('./components/mainMid/mapCopy.vue')['default']
    Mid1: typeof import('./components/mainMid/mid1.vue')['default']
    Mid11: typeof import('./components/mainMid/mid11.vue')['default']
    Mid2: typeof import('./components/mainMid/mid2.vue')['default']
    MidUnderEcharts: typeof import('./components/mainMid/midUnderEcharts.vue')['default']
    Right1: typeof import('./components/mainRight/right1.vue')['default']
    Right2: typeof import('./components/mainRight/right2.vue')['default']
    Right3: typeof import('./components/mainRight/right3.vue')['default']
    Right4: typeof import('./components/mainRight/right4.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Threejs: typeof import('./components/mainMid/threejs.vue')['default']
    ThreeShow: typeof import('./components/mainMid/threeShow.vue')['default']
  }
}
